### ISSUE TITLE
python support

### ISSUE THREAD

**Issue by MuhsinFatih** [jmihelcic/colored-regions#13]
Just wanted to say, by luck this already works :)
Python region syntax is the same as C# region syntax in vscode, so you can just add a test case and announoce python support :)

I can confirm:
![image](https://user-images.githubusercontent.com/8341386/81138209-575a6c00-8f2f-11ea-9206-ba849dda897c.png)

**Comment by Kasheftin** [comment]
It was added.
Python multiline `''' region ... end region '''` comments support was added as well in v0.0.4.
