### ISSUE TITLE
Sub region doesn't get the color

### ISSUE THREAD

**Issue by mathias22osterhagen22** [jmihelcic/colored-regions#14]
When it is a region inside another region the color of the sub-region doesn't take the good color.

**Got:**
![image](https://user-images.githubusercontent.com/60438474/93472341-ca6bea00-f8f4-11ea-9cbe-a7dc9322cfe6.png)

**Expected:**
![image](https://user-images.githubusercontent.com/60438474/93472474-fa1af200-f8f4-11ea-8afb-81b83a6c5c32.png)

**Comment by Kasheftin** [comment]
Nested regions support was added in v0.0.4.
