### ISSUE TITLE
Extension no longer works

### ISSUE THREAD

**Issue by lonix1** [jmihelcic/colored-regions#15]
On latest vscode 1.52.1 - extension no longer works. :(

It was an awesome extension! I hope @jmihelcic will decide to revive it someday.

Thanks, I enjoyed using it.

**Comment by jmihelcic** [comment]
Hey there @lonix1 ! 
I'm super glad that you're enjoying this little extension. 

Since the extension stopped working, I guess it's time to do something. I've been wanting to update it, but the API changed so much it's easier to just make a new one, but I never found the time.

So... you'll be glad to hear I just started work on Colored Regions 2. I'll try to put out a basic version (carbon copy) ASAP with some small improvements, then update it with all the bugs / feature requests that have collected until now.

Have a nice one!

**Comment by lonix1** [comment]
Update us on this repo, so we know when we can start beta testing it!!!

It's a **must have** extension. Super excited! :grinning:

**Comment by jmihelcic** [comment]
Hey @lonix1, just a quick question. Are you sure the extension stopped working, and that it's not something else? It works perfectly on the latest VSCode for me. 🤔

**Comment by lonix1** [comment]
Possibly... Is there a log I can check somewhere?

**Comment by lonix1** [comment]
Possibly... Is there a log I can check somewhere?

I do this:
````json
"coloredRegions.namedColors": {
  "foo": "rgba(52,152,219)",
}
````

But that doesn't apply to either of these cases:
````csharp
#region foo
#endregion

//#region foo
//#endregion
````

This also doesn't work:
````csharp
//#region[rgba(52,152,219)] foo
//#endregion
````

When the region is expanded, I expect it to be colored, but it is not.

When the region is folded, the line is shown in some other color - maybe a different extension, or a built in setting. I'm not sure as this is the only region extension I'm using.

I'm using the latest vscode with dark mode. I'm using it for c#.

**Comment by jmihelcic** [comment]
If this is exactly how you defined it:
```
"foo": "rgba(52,152,219)",
```
Then you're missing an `alpha` value at the end like: `rgba(52,152,219,0.5)`

**Comment by lonix1** [comment]
Oops typo... I use alpha values in my config.

Doesn't make a difference unfortunately. :cry:

**Comment by lonix1** [comment]
I'm thinking that if you're working on the next version, some of these issues are probably not worth pursuing - once you release a new version, these old issues will simply disappear.

API changes and so on.

**Comment by lonix1** [comment]
I found the problem!!!

`#region foo` should be `#region [foo]`

:smile: 

Still looking forward to the new version though!
