### ISSUE TITLE
[Question] Color when region is collapsed

### ISSUE THREAD

**Issue by lonix1** [jmihelcic/colored-regions#16]
Hey again @jmihelcic.

- *If extension is disabled:* when I collapse a region it shows a single line with a green background (I didn't configure this color, don't know where it comes from)
- *If extension enabled:* it still shows the green line

Is this normal - does it work this way for you too? I expected it to use my configured color (not green).

I looked for a default setting for this, but can't find anything. I doubt it's another extension as yours is the only one I'm using for colors.

**Comment by jmihelcic** [comment]
If it's there when the extension is disabled, then it's not from the extension. 
Also there is some default coloring by VSCode for the collapsed regions, that is overlaid over the Colored Regions colors. It happens to me too, but my default color is a transparent grey so its not as noticeable.

**Comment by lonix1** [comment]
Yeah that's what I wanted to know, it's not just me! :)

When collapsed, is it possible for the extension to "color over" the default somehow, so it shows the proper (user configured) color?

**Comment by Kasheftin** [comment]
It should go from the used theme. By default, folded blocks in the vs code have a light grey background which overlays with the background, provided by the colored-regions. You should update `editor.foldBackground` setting to get rid of that.
