### ISSUE TITLE
[Bug] Does not honour named colour with spaces

### ISSUE THREAD

**Issue by lonix1** [jmihelcic/colored-regions#17]
````js
"coloredRegions.namedColors": {
  "foo":     "rgba(100, 100, 100,  .5)",
  "bar baz": "rgba(200, 200, 200,  .5)",           // this fails
}
````

When `[bar baz]` is used in code, it doesn't properly colour that region.

**Comment by Kasheftin** [comment]
It's supported in v0.0.4. Furthermore, it's possible to define ` bar baz `, `bar baz`, `Bar Baz`, `barbaz` colors, and it's smart enough to choose an exact match at first, then trim, then lowercase, then no whitespace names.
