### ISSUE TITLE
Suggestion: Parse name of region and color independent of positioning

### ISSUE THREAD

**Issue by NTTAKR** [jmihelcic/colored-regions#18]
Hi! 
Your extension has a big impact on code-review and I also like to mark pending refactorings with colored blocks. 

A minor issue for me is that I cannot use 

`//#region NAME OF THE REGION [rgba(255, 0, 0, 0.2)]
`
as the extension does not recognize the color if any text is before it. 
I like to name regions, and the name should precede the color. 
Could you please use a more relaxed search, so that I can use this syntax too? 

Thanks for your work
   Andreas

**Comment by 4lch4** [comment]
I'd love to see something like this implemented. I've forked the repository, and I'll poke around to see if I can't come up with something and submit a PR.

**Comment by Kasheftin** [comment]
Flexible comment and color specification is supported in v0.0.4.
