### ISSUE TITLE
Region color changes when you collapse code inside it

### ISSUE THREAD

**Issue by byi8220** [jmihelcic/colored-regions#2]
If you collapse code inside a region, the region decoration seems to be applied multiple times.

![regiondupe](https://user-images.githubusercontent.com/24833703/36963379-f1dd4e62-2020-11e8-888c-1db6d97effc9.png)

I have a similar issue and I'm not sure how to fix it myself.

**Comment by jmihelcic** [comment]
This seems to be a bug with VSCode. Will keep an eye out for a possible fix in the mean time. A "not-so-elegant" solution would be to use the raw color at opacity 1.0, but that would make it bound to the specific theme you are using.

**Comment by lwthatcher** [comment]
Is there a way to compute what the resulting color would be when applying a color with `opacity != 1.0` to the current background, then set _that_ color as your background color with opacity 1.0?

**Comment by Kasheftin** [comment]
I believe it works as expected now. Folded regions have a slightly different background, but this can be solved by customizing `editor.foldBackground` setting.
