### ISSUE TITLE
AL (Business Central) Support

### ISSUE THREAD

**Issue by m3koenig** [jmihelcic/colored-regions#20]
Hi :)

I like what I see but I need it for AL (https://github.com/microsoft/AL).
Its the same like PowerShell or C#.

**Comment by m3koenig** [comment]
nevermind...I got it.
![image](https://user-images.githubusercontent.com/9989457/234572277-a0643eb7-a2e1-4169-a923-146e2bbe4d22.png)

I had to add the "Tag".
No chance without the tag or?
Every #region should be colorfull :)

**Comment by Kasheftin** [comment]
Regions without a `Tag` are supported in v0.0.4.
