### ISSUE TITLE
false-positive coloring in v0.0.4

### ISSUE THREAD

**Issue by micalevisk** [jmihelcic/colored-regions#22]
starting from v0.0.4, now my Terraform file looks like this:

![image](https://github.com/jmihelcic/colored-regions/assets/13461315/6a398089-4361-4ec5-a7c7-942a84da094c)

is this a bug? prior to v0.0.4, the coloring was not enabled, which is the expected behavior (to me)

**Comment by Kasheftin** [comment]
I can confirm the regex to start the region became too strong. It was fixed in v0.0.5.
