### ISSUE TITLE
Selection not working inside colored blocks

### ISSUE THREAD

**Issue by Rokuem** [jmihelcic/colored-regions#4]
![image](https://user-images.githubusercontent.com/26756006/38633635-aadbf2e6-3d96-11e8-8907-949affaa4de1.png)
In this case i have everything selected. U can see a red line at the left, that is my selection color. The content in the colored area is selected but i can't see it, is it just me or is a know problem?

**Comment by jmihelcic** [comment]
Interesting. Did you by any chance define your colors with full (1.0) alpha value? It seems that the region color is overlaid over the selection highlight, thus making it invisible.

**Comment by Rokuem** [comment]
oh, i see, silly me :P, yeah, they had full (1.0) alpha value, i guess i expected the select effect to have a higher priority.
![image](https://user-images.githubusercontent.com/26756006/38642539-bc5dc3e0-3db0-11e8-9e10-a74f026cf27a.png)

because when u place the mouse on a term the term selection will have a higher priority, so i got confused, ty for replying :)
