### ISSUE TITLE
[Feature Request] Provide default/random color if no color defined

### ISSUE THREAD

**Issue by SnakyBeaky** [jmihelcic/colored-regions#9]
A setting to automatically assign a default/random color to regions without [rgba(x,y,z,w)].

This would be useful for those who don't want to pollute their code with rgba colors but still want the regions to be easily distinguishable from each other.

**Comment by hikidd** [comment]
agree

**Comment by Christilut** [comment]
Came here to ask this

**Comment by fk1blow** [comment]
aaaaand, resurected

way to cool to not have this, please!

**Comment by Kasheftin** [comment]
`coloredRegions.colorRange` setting was introduced in v0.0.4. It automatically assigns the next color if the exact one is not specified.
